### ISSUE TITLE
not enough RAM 

### ISSUE THREAD

**Issue by tpeg5stan** [IBM-Bluemix/aspnet-core-todo#1]
Hello,

I wanted to use your app on Bluemix with my account, but I noticed it failed on deployment.
By changing the amount of RAM provided, I was able to have the app working.

Is it possible to just chnage the value of 256 in the manifest.yml to 512, so that I won't have problems at startup ?

Thanks in advance.

**Comment by itzunagi** [comment]
Thanks for bringing this up, it's been fixed now.
